---
- hosts: serverweb
- name: Setting up LAMP Website
  user: root
  hosts: serverweb
  become: yes
  tasks:
    - name: latest version of all required packages installed
      apt:
        name:
          - mariadb-server
          - php
          - php-mysql
        state: latest

    - name: mariadb enabled and running
      service:
        name: mariadb
        enabled: true
        state: started
